default_context:
  name: "ezros"
  version: "0.1.0"
  slug: "ezros"
  command: "ezros"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "Ease your ROS development"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "ease ros development"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "ezros"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "ezros"
  github_action: "n"
  ml: "n"
  editor: "vscode"
<<<<<<< HEAD
  url: "https://github.com/achillesrasquinha/ezros"
  ros: "y"
=======
  url: "https://github.com/achillesrasquinha/ezros"
>>>>>>> template/master
