#!/usr/bin/env python

import ezros
import cv2
import base64

from bpyutils.util.string import safe_decode

WIDTH   = 480
HEIGHT  = 360

node    = ezros.Node("camera")
capture = cv2.VideoCapture(0)

@node.pub("/image", rate = 30, queue_size = 10)
def handle_image(message):
    _, frame = capture.read()

    width, height = node.p("width", WIDTH), node.p("height", HEIGHT)
    
    resized = cv2.resize(frame, (height, width))

    encoded = base64.b64encode(resized)
    decoded = safe_decode(encoded)

    # message.width  = width
    # message.height = height
    message.data   = decoded

    return message

if __name__ == "__main__":
    node.run()