#!/usr/bin/env python

import ezros

node = ezros.Node("camera")

@node.pub("/image", "ezros.msg.Image", rate = 10, queue_size = 10)
def handle_image(message):
    return message

if __name__ == "__main__":
    node.run()